// band3 - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/band3_config.h"
#include "generated/band3_init.h"

#include <rex/rex_app.h>
#include <rex/cvar.h>
#include <rex/logging.h>

#include "config.h"

class Band3App : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    REXCVAR_SET(log_file, std::string("band3.log"));
    REXCVAR_SET(log_level, std::string("info"));
    return std::unique_ptr<Band3App>(new Band3App(ctx, "band3",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }

  void OnPostSetup() override {
    band3::LoadConfig();
    rex::cvar::SetFlagByName("log_level", band3::GetConfig().log_level);
  }

  void OnCreateDialogs(rex::ui::ImGuiDrawer* drawer) override {
    auto& cfg = band3::GetConfig();
    if (cfg.fullscreen) {
      window()->SetFullscreen(true);
    }
  }
};

REX_DEFINE_APP(band3, Band3App::Create)
