// band3 - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/band3_config.h"
#include "generated/band3_init.h"

#include <rex/rex_app.h>
#include <rex/cvar.h>
#include <rex/logging.h>
#include <rex/ui/imgui_dialog.h>
#include <imgui.h>

#include "config.h"

class DebugOverlayDialog : public rex::ui::ImGuiDialog {
 public:
  explicit DebugOverlayDialog(rex::ui::ImGuiDrawer* imgui_drawer)
      : rex::ui::ImGuiDialog(imgui_drawer) {}

 protected:
  void OnDraw(ImGuiIO& io) override {
    ImGui::SetNextWindowPos(ImVec2(10, 10), ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(220, 60), ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowBgAlpha(0.5f);
    if (ImGui::Begin("Debug##overlay", nullptr, ImGuiWindowFlags_NoCollapse)) {
      ImGui::Text("%.1f FPS (%.2f ms)", io.Framerate, 1000.0f / io.Framerate);
    }
    ImGui::End();
  }
};

class Band3App : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;
  std::unique_ptr<DebugOverlayDialog> debug_overlay_;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    REXCVAR_SET(log_file, std::string("band3.log"));
    REXCVAR_SET(log_level, std::string("info"));
    return std::unique_ptr<Band3App>(new Band3App(ctx, "band3",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings, REXCRT_HEAP}));
  }

  void OnPostSetup() override {
    band3::LoadConfig();
    rex::cvar::SetFlagByName("log_level", band3::GetConfig().log_level);
    rex::cvar::SetFlagByName("audio_maxqframes", std::to_string(band3::GetConfig().max_queued_frames));
  }

  void OnCreateDialogs(rex::ui::ImGuiDrawer* drawer) override {
    auto& cfg = band3::GetConfig();
    if (cfg.fullscreen) {
      window()->SetFullscreen(true);
    }

    if (cfg.debug_overlay && drawer) {
      debug_overlay_ = std::make_unique<DebugOverlayDialog>(drawer);
    } else {
      debug_overlay_.reset();
    }
  }
};

REX_DEFINE_APP(band3, Band3App::Create)
